#Give sudo permission
sudo: required

#Use docker service
services:
  - docker

#build image before install
before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

#scripts to run for testing purpose
script:
  - docker run stephengrider/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "nealshendockerreact"
  env: "Nealshendockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-5678990322157"
  bucket_path: "nealshendockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"